from lispinterpreter import tokenise


def test_tokenise():
    input_output_pairs = {
        "(mult 3 (add 2 3))": ["(", "mult", "3", "(", "add", "2", "3", ")", ")"],
        "(let x 2 (mult x (let x 3 y 4 (add x y))))": [
            "(",
            "let",
            "x",
            "2",
            "(",
            "mult",
            "x",
            "(",
            "let",
            "x",
            "3",
            "y",
            "4",
            "(",
            "add",
            "x",
            "y",
            ")",
            ")",
            ")",
            ")",
        ],
        "(let x 1 y 2 x (add x y) (add x y))": [
            "(",
            "let",
            "x",
            "1",
            "y",
            "2",
            "x",
            "(",
            "add",
            "x",
            "y",
            ")",
            "(",
            "add",
            "x",
            "y",
            ")",
            ")",
        ],
        "(let x 2 (add (let x 3 (let x 4 x)) x))": [
            "(",
            "let",
            "x",
            "2",
            "(",
            "add",
            "(",
            "let",
            "x",
            "3",
            "(",
            "let",
            "x",
            "4",
            "x",
            ")",
            ")",
            "x",
            ")",
            ")",
        ],
    }
    for expr, expected_output in input_output_pairs.items():
        output = list(tokenise(expr))
        assert expected_output == output
